version: '3.9'
services:
  mongo:
    image: mongo:6.0
    container_name: lba_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mhdtahiri01
      MONGO_INITDB_ROOT_PASSWORD: medtahiri1
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: lba_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mhdtahiri01
      ME_CONFIG_MONGODB_ADMINPASSWORD: medtahiri1
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  
      - "1025:1025"   

volumes:
  mongo_data:
